import { createElement, Fragment, type ReactNode } from "react";
import { LABELS, type Labels } from "../lib/labels";

const plural = (count: number, one: string, few: string, many: string) => {
  const mod10 = count % 10;
  const mod100 = count % 100;
  return mod10 === 1 && mod100 !== 11
    ? one
    : mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)
      ? few
      : many;
};

export const ru: Labels = {
  ...LABELS,
  close: "Закрыть",
  columns: "Столбцы",
  edit: "Изменить",
  reorder: (item) => `Изменить порядок: ${item}`,
  lifted: (item, position, count) =>
    `${item} поднят, позиция ${position} из ${count}. Стрелки перемещают, пробел размещает, Escape отменяет.`,
  movedTo: (position, count) => `Позиция ${position} из ${count}`,
  dropped: (item, position) => `${item} размещён на позиции ${position}`,
  reorderCancelled: (item) => `Перемещение отменено, ${item} возвращён`,
  lastHour: "Последний час",
  last24Hours: "Последние 24 часа",
  last7Days: "Последние 7 дней",
  last30Days: "Последние 30 дней",
  customRange: "Другой диапазон…",
  from: "С",
  to: "По",
  keyboardShortcuts: "Сочетания клавиш",
  back: "Назад",
  done: "Готово",
  stepOf: (step, count) => `${step} из ${count}`,
  moveWithArrows: "Перемещайте стрелками",
  minimize: "Свернуть",
  maximize: "Развернуть",
  restore: "Восстановить",
  dismiss: "Скрыть",
  remove: "Удалить",
  clear: "Очистить",
  loading: "Загрузка",
  search: "Поиск…",
  searchLabel: "Поиск",
  select: "Выберите…",
  none: "— нет —",
  notifications: "Уведомления",
  navigation: "Навигация",
  openNavigation: "Открыть навигацию",
  onThisPage: "На этой странице",
  breadcrumb: "Навигационная цепочка",
  pagination: "Постраничная навигация",
  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  pageSize: "Элементов на странице",
  perPage: (count) => `${count} / стр.`,
  itemRange: (from, to, total) =>
    `${from.toLocaleString("ru-RU")}–${to.toLocaleString("ru-RU")} из ${total.toLocaleString("ru-RU")}`,
  resize: "Изменить размер",
  customColor: "Другой цвет",
  unsaved: "Несохранённые изменения",
  required: "Обязательное поле",
  minValue: (min) => `Минимум: ${min}`,
  maxValue: (max) => `Максимум: ${max}`,
  minLength: (count) => `Минимум ${count} ${plural(count, "символ", "символа", "символов")}`,
  maxLength: (count) => `Максимум ${count} ${plural(count, "символ", "символа", "символов")}`,
  minCount: (count) => `Выберите минимум ${count}`,
  maxCount: (count) => `Выберите максимум ${count}`,
  invalidFormat: "Неверный формат",
  newItems: "новое",
  skipToContent: "Перейти к содержимому",
  resetDefaults: "Сбросить настройки",
  noData: "Нет данных",
  commandPalette: "Палитра команд",
  commandPlaceholder: "Введите команду или запрос…",
  noCommands: (query) => (query ? `Нет команд по запросу «${query}»` : "Нет команд"),
  confirm: (action: ReactNode) => createElement(Fragment, null, action, "?"),
  barChart: "Столбчатая диаграмма",
  lineChart: "Линейный график",
  visibleRange: "Видимый диапазон",
  stackedBarChart: "Составная столбчатая диаграмма",
  donutChart: "Кольцевая диаграмма",
  waffleChart: "Вафельная диаграмма",
  treemap: "Древовидная карта",
  scatterChart: "Точечная диаграмма",
  total: "Всего",
  target: "цель",
  heatmap: "Тепловая карта",
  showTable: "Показать таблицу",
  showChart: "Показать график",
  copy: "Копировать",
  copied: "Скопировано",
  rename: "Переименовать",
  increment: "Увеличить",
  decrement: "Уменьшить",
  minimum: "Минимум",
  maximum: "Максимум",
  moreCount: (count) => `+${count}`,
  moreItems: (count) => `Ещё ${count}`,
  scrollBack: "Прокрутить назад",
  scrollForward: "Прокрутить вперёд",
  jumpToLatest: "К последним",
  selectedCount: (count) => `Выбрано: ${count}`,
  clearSelection: "Снять выделение",
  selectAll: "Выбрать всё",
  selectRow: "Выбрать строку",
  ok: "ОК",
  cancel: "Отмена",
  apply: "Применить",
  filter: "Фильтр…",
  noResults: "Ничего не найдено",
  dropFiles: "Перетащите файлы сюда или",
  browseFiles: "выберите",
  wrapLines: "Переносить строки",
  codeEditor: "Редактор кода",
  moreActions: "Другие действия",
  showOptions: "Показать параметры",
  removeToken: (label) => `Удалить ${label}`,
  previous: "Назад",
  next: "Далее",
  zoomIn: "Увеличить",
  zoomOut: "Уменьшить",
  fitToScreen: "Вписать в экран",
  imageCounter: (index, count) => `${index} / ${count}`,
  selectItem: "Выбрать",
  logLevels: "Уровни",
  noLevel: "БЕЗ УР.",
  showPassword: "Показать пароль",
  hidePassword: "Скрыть пароль",
  pinDigit: (index, count) => `Цифра ${index} из ${count}`,
  showMore: "Показать больше",
  showLess: "Показать меньше",
  copyValue: "Копировать значение",
  copyPath: "Копировать путь",
  jsonItems: (count) => `${count} ${plural(count, "элемент", "элемента", "элементов")}`,
  jsonKeys: (count) => `${count} ${plural(count, "ключ", "ключа", "ключей")}`,
  stepComplete: "завершён",
  stepCurrent: "текущий шаг",
  stepError: "содержит ошибки",
  retry: "Повторить",
  loadFailed: "Не удалось загрузить",
  colorArea: "Светлота и насыщенность",
  hue: "Оттенок",
  opacity: "Прозрачность",
  pickFromScreen: "Выбрать цвет с экрана",
};

export const ruAppearance: Record<string, ReactNode> = {
  "appearance.color.title": "Цвет",
  "appearance.shape.title": "Форма",
  "appearance.type.title": "Плотность и шрифт",
  "appearance.effects.title": "Эффекты",
  "appearance.accent.label": "Акцент",
  "appearance.neutral.label": "Оттенок поверхностей",
  "appearance.neutral.hint": "Оттенок фона и текста",
  "appearance.radius.label": "Радиус углов",
  "appearance.pill.label": "Круглые элементы",
  "appearance.pill.hint": "Полностью скруглённые кнопки и поля",
  "appearance.corners.label": "Углы",
  "appearance.corners.hint":
    "Squircle использует плавные кривые, если браузер поддерживает corner-shape; квадратные — без скруглений вообще, включая кнопки и круги",
  "appearance.layout.label": "Компоновка",
  "appearance.layout.hint": "Острова разделяют части на панели; встроенный режим объединяет содержимое",
  "appearance.density.label": "Плотность",
  "appearance.font.label": "Шрифт",
  "appearance.fontSize.label": "Размер текста",
  "appearance.material.label": "Поверхности",
  "appearance.material.hint": "Непрозрачные, полупрозрачные или стеклянные панели",
  "appearance.glass.label": "Стекло",
  "appearance.glass.hint": "Полупрозрачные меню, диалоги и панели с размытием",
  "appearance.glass.blur.label": "Размытие",
  "appearance.motion.label": "Анимация",
  "appearance.corners.option.round": "Круглые",
  "appearance.corners.option.squircle": "Squircle",
  "appearance.corners.option.square": "Квадратные",
  "appearance.layout.option.islands": "Острова",
  "appearance.layout.option.inset": "Встроенный",
  "appearance.density.option.compact": "Компактно",
  "appearance.density.option.default": "Обычно",
  "appearance.density.option.comfortable": "Просторно",
  "appearance.font.option.geist": "Geist",
  "appearance.font.option.inter": "Inter",
  "appearance.font.option.system": "Системный",
  "appearance.font.option.mono": "Моноширинный",
  "appearance.material.option.solid": "Сплошные",
  "appearance.material.option.veil": "Вуаль",
  "appearance.material.option.frost": "Иней",
  "appearance.material.option.liquid": "Жидкое стекло",
  "appearance.motion.option.system": "Системная",
  "appearance.motion.option.full": "Полная",
  "appearance.motion.option.off": "Выключена",
};

export const ruTranslate = (key: string, fallback: ReactNode): ReactNode => ruAppearance[key] ?? fallback;
