import { globalStyle } from "@vanilla-extract/css";
import { tokens } from "./tokens.css";

globalStyle(":where(:root)", {
  colorScheme: "dark",
  vars: {
    [tokens.accent]: "oklch(0.57 0.2 277)",
    [tokens.neutralH]: "260",
    [tokens.neutralC]: "0.012",
    [tokens.radius]: "18px",
    [tokens.radiusControl]: "10px",
    [tokens.cornerShape]: "round",
    [tokens.roundness]: "1",
    [tokens.linecap]: "round",
    [tokens.density]: "1",
    [tokens.fontSize]: "13px",
    [tokens.iconStroke]: "1.75",
    [tokens.fontDefault]:
      '"Geist Variable", "Geist", "Inter Variable", "Inter", ui-sans-serif, system-ui, sans-serif',
    [tokens.fontSans]: `${tokens.fontDefault}`,
    [tokens.fontMono]:
      '"Geist Mono Variable", "Geist Mono", "JetBrains Mono", ui-monospace, "Cascadia Code", Consolas, monospace',
    [tokens.glass]: "1",
    [tokens.systemMotion]: "1",
    [tokens.motion]: `${tokens.systemMotion}`,
    [tokens.systemAnimationState]: "running",
    [tokens.animationState]: `${tokens.systemAnimationState}`,
  },
});

globalStyle(":where(:root, [data-rk-scope])", {
  vars: {
    [tokens.bg]: `oklch(0.145 ${tokens.neutralC} ${tokens.neutralH})`,
    [tokens.surface1]: `oklch(0.185 calc(${tokens.neutralC} * 1.6) ${tokens.neutralH})`,
    [tokens.surface2]: `oklch(0.225 calc(${tokens.neutralC} * 2) ${tokens.neutralH})`,
    [tokens.surface3]: `oklch(0.27 calc(${tokens.neutralC} * 2.35) ${tokens.neutralH})`,
    [tokens.surface4]: `oklch(0.32 calc(${tokens.neutralC} * 2.6) ${tokens.neutralH})`,
    [tokens.sunken]: `oklch(0.125 calc(${tokens.neutralC} * 0.9) ${tokens.neutralH})`,
    [tokens.shade]: `0.08 calc(${tokens.neutralC} * 2) ${tokens.neutralH}`,
    [tokens.tint]: `0.92 calc(${tokens.neutralC} * 2.5) ${tokens.neutralH}`,
    [tokens.line]: `oklch(${tokens.tint} / 0.08)`,
    [tokens.lineStrong]: `oklch(${tokens.tint} / 0.15)`,
    [tokens.controlEdge]: `oklch(${tokens.tint} / 0.4)`,
    [tokens.spectrum]:
      "conic-gradient(\n    from 0deg,\n    oklch(0.75 0.18 0),\n    oklch(0.75 0.18 90),\n    oklch(0.75 0.18 180),\n    oklch(0.75 0.18 270),\n    oklch(0.75 0.18 360)\n  )",
    [tokens.hover]: `oklch(${tokens.tint} / 0.05)`,
    [tokens.press]: `oklch(${tokens.tint} / 0.09)`,
    [tokens.well]: `oklch(${tokens.shade} / 0.32)`,
    [tokens.wellSoft]: `oklch(${tokens.shade} / 0.18)`,
    [tokens.text]: `oklch(0.965 calc(${tokens.neutralC} * 0.5) ${tokens.neutralH})`,
    [tokens.text2]: `oklch(0.77 calc(${tokens.neutralC} * 2.5) ${tokens.neutralH})`,
    [tokens.text3]: `oklch(0.7 calc(${tokens.neutralC} * 2.8) ${tokens.neutralH})`,
    [tokens.inverse]: `oklch(0.965 calc(${tokens.neutralC} * 0.7) ${tokens.neutralH})`,
    [tokens.onInverse]: `oklch(0.17 calc(${tokens.neutralC} * 1.6) ${tokens.neutralH})`,
    [tokens.labelLight]: "oklch(1 0 0)",
    [tokens.labelDark]: "oklch(0.08 0 0)",
    [tokens.scrim]: `oklch(${tokens.shade} / 0.62)`,
    [tokens.accentHover]: `oklch(from ${tokens.accent} calc(l - 0.02) c h)`,
    [tokens.accentSoft]: `color-mix(in oklab, ${tokens.accent} 16%, transparent)`,
    [tokens.accentLine]: `color-mix(in oklab, ${tokens.accent} 55%, transparent)`,
    [tokens.onAccent]: `var(
    --rk-accent-label,
    oklch(from ${tokens.accent} clamp(0.16, (0.73 - l) * 100, 0.99) 0 0)
  )`,
    [tokens.onAccentHover]: `var(--rk-accent-hover-label, ${tokens.onAccent})`,
    [tokens.accentText]: `oklch(from ${tokens.accent} max(l, 0.82) min(c, 0.11) h)`,
    [tokens.success]: "oklch(0.78 0.15 162)",
    [tokens.warn]: "oklch(0.83 0.15 78)",
    [tokens.danger]: "oklch(0.68 0.2 24)",
    [tokens.info]: "oklch(0.75 0.13 245)",
    [tokens.onDanger]: `${tokens.onInverse}`,
    [tokens.chart1]: "oklch(0.66 0.15 250)",
    [tokens.chart2]: "oklch(0.66 0.16 45)",
    [tokens.chart3]: "oklch(0.66 0.11 185)",
    [tokens.chart4]: "oklch(0.62 0.17 300)",
    [tokens.chart5]: "oklch(0.66 0.16 135)",
    [tokens.chart6]: "oklch(0.64 0.18 355)",
    [tokens.chartGrid]: `oklch(${tokens.tint} / 0.07)`,
    [tokens.chartIdle]: `${tokens.surface4}`,
    [tokens.chartSeqLo]: "oklch(0.26 0.035 250)",
    [tokens.chartSeqHi]: "oklch(0.86 0.12 250)",
    [tokens.space]: `calc(4px * ${tokens.density})`,
    [tokens.hSm]: `calc(28px * ${tokens.density})`,
    [tokens.hMd]: `calc(34px * ${tokens.density})`,
    [tokens.hLg]: `calc(42px * ${tokens.density})`,
    [tokens.radiusSm]: `calc(${tokens.radius} * 0.45)`,
    [tokens.radiusMd]: `calc(${tokens.radius} * 0.7)`,
    [tokens.radiusLg]: `${tokens.radius}`,
    [tokens.radiusXl]: `calc(${tokens.radius} * 1.4)`,
    [tokens.radiusPill]: `calc(999px * ${tokens.roundness})`,
    [tokens.radiusRound]: `calc(50% * ${tokens.roundness})`,
    [tokens.pad]: `calc(${tokens.space} * 4)`,
    [tokens.text2xs]: `max(11px, calc(${tokens.fontSize} * 0.8))`,
    [tokens.textXs]: `calc(${tokens.fontSize} * 0.85)`,
    [tokens.textSm]: `calc(${tokens.fontSize} * 0.93)`,
    [tokens.textMd]: `${tokens.fontSize}`,
    [tokens.textLg]: `calc(${tokens.fontSize} * 1.15)`,
    [tokens.textXl]: `calc(${tokens.fontSize} * 1.4)`,
    [tokens.text2xl]: `calc(${tokens.fontSize} * 1.85)`,
    [tokens.text3xl]: `calc(${tokens.fontSize} * 2.6)`,
    [tokens.textDisplay]: `calc(${tokens.fontSize} * 3.6)`,
    [tokens.highlight]: `inset 0 1px 0 oklch(${tokens.tint} / 0.045)`,
    [tokens.shadow1]: `${tokens.highlight}, 0 1px 2px oklch(${tokens.shade} / 0.25), 0 0 0 1px oklch(${tokens.tint} / 0.035)`,
    [tokens.shadow2]: `inset 0 1px 0 oklch(${tokens.tint} / 0.06), 0 0 0 1px oklch(${tokens.tint} / 0.05),
    0 10px 30px -12px oklch(${tokens.shade} / 0.55)`,
    [tokens.shadowPop]: `inset 0 1px 0 oklch(${tokens.tint} / 0.07), 0 0 0 1px ${tokens.lineStrong},
    0 24px 60px -16px oklch(${tokens.shade} / 0.7)`,
    [tokens.blur]: `calc(${tokens.glass} * 20px)`,
    [tokens.glassBg]: `color-mix(in oklab, ${tokens.surface2} calc(100% - ${tokens.glass} * 22%), transparent)`,
    [tokens.hatch]: `repeating-linear-gradient(-45deg, oklch(${tokens.tint} / 0.09) 0 1.5px, transparent 1.5px 6px)`,
    [tokens.dur]: `calc(160ms * ${tokens.motion})`,
    [tokens.durSlow]: `calc(320ms * ${tokens.motion})`,
    [tokens.ease]: "cubic-bezier(0.2, 0, 0, 1)",
    [tokens.easeOut]: "cubic-bezier(0.22, 1, 0.36, 1)",
    [tokens.spring]: "cubic-bezier(0.34, 1.45, 0.64, 1)",
    [tokens.focus]: `${tokens.accent}`,
  },
});

globalStyle(":root", {
  "@media": {
    "(prefers-reduced-motion: reduce)": {
      vars: {
        [tokens.systemMotion]: "0",
        [tokens.systemAnimationState]: "paused",
        [tokens.motion]: `${tokens.systemMotion}`,
      },
    },
  },
});
