import { createGlobalThemeContract } from "@vanilla-extract/css";

export const tokens = createGlobalThemeContract({
  animationState: "rk-animation-state",
  systemAnimationState: "rk-system-animation-state",
  accent: "rk-accent",
  neutralH: "rk-neutral-h",
  neutralC: "rk-neutral-c",
  radius: "rk-radius",
  radiusControl: "rk-radius-control",
  cornerShape: "rk-corner-shape",
  roundness: "rk-roundness",
  linecap: "rk-linecap",
  density: "rk-density",
  fontSize: "rk-font-size",
  iconStroke: "rk-icon-stroke",
  fontDefault: "rk-font-default",
  fontSans: "rk-font-sans",
  fontMono: "rk-font-mono",
  glass: "rk-glass",
  systemMotion: "rk-system-motion",
  motion: "rk-motion",
  bg: "rk-bg",
  surface1: "rk-surface-1",
  surface2: "rk-surface-2",
  surface3: "rk-surface-3",
  surface4: "rk-surface-4",
  sunken: "rk-sunken",
  shade: "rk-shade",
  tint: "rk-tint",
  line: "rk-line",
  lineStrong: "rk-line-strong",
  controlEdge: "rk-control-edge",
  spectrum: "rk-spectrum",
  hover: "rk-hover",
  press: "rk-press",
  well: "rk-well",
  wellSoft: "rk-well-soft",
  text: "rk-text",
  text2: "rk-text-2",
  text3: "rk-text-3",
  inverse: "rk-inverse",
  onInverse: "rk-on-inverse",
  scrim: "rk-scrim",
  accentHover: "rk-accent-hover",
  accentSoft: "rk-accent-soft",
  accentLine: "rk-accent-line",
  onAccent: "rk-on-accent",
  onAccentHover: "rk-on-accent-hover",
  labelLight: "rk-label-light",
  labelDark: "rk-label-dark",
  accentText: "rk-accent-text",
  success: "rk-success",
  warn: "rk-warn",
  danger: "rk-danger",
  info: "rk-info",
  onDanger: "rk-on-danger",
  chart1: "rk-chart-1",
  chart2: "rk-chart-2",
  chart3: "rk-chart-3",
  chart4: "rk-chart-4",
  chart5: "rk-chart-5",
  chart6: "rk-chart-6",
  chartGrid: "rk-chart-grid",
  chartIdle: "rk-chart-idle",
  chartSeqLo: "rk-chart-seq-lo",
  chartSeqHi: "rk-chart-seq-hi",
  space: "rk-space",
  hSm: "rk-h-sm",
  hMd: "rk-h-md",
  hLg: "rk-h-lg",
  radiusSm: "rk-radius-sm",
  radiusMd: "rk-radius-md",
  radiusLg: "rk-radius-lg",
  radiusXl: "rk-radius-xl",
  radiusPill: "rk-radius-pill",
  radiusRound: "rk-radius-round",
  pad: "rk-pad",
  text2xs: "rk-text-2xs",
  textXs: "rk-text-xs",
  textSm: "rk-text-sm",
  textMd: "rk-text-md",
  textLg: "rk-text-lg",
  textXl: "rk-text-xl",
  text2xl: "rk-text-2xl",
  text3xl: "rk-text-3xl",
  textDisplay: "rk-text-display",
  highlight: "rk-highlight",
  shadow1: "rk-shadow-1",
  shadow2: "rk-shadow-2",
  shadowPop: "rk-shadow-pop",
  blur: "rk-blur",
  glassBg: "rk-glass-bg",
  hatch: "rk-hatch",
  dur: "rk-dur",
  durSlow: "rk-dur-slow",
  ease: "rk-ease",
  easeOut: "rk-ease-out",
  spring: "rk-spring",
  focus: "rk-focus",
});

// Explicit inverse values avoid referring to tokens this card overrides itself.
export const inverse = {
  text: `oklch(0.17 ${tokens.neutralC} ${tokens.neutralH})`,
  secondary: `oklch(0.42 ${tokens.neutralC} ${tokens.neutralH})`,
  muted: `oklch(0.52 ${tokens.neutralC} ${tokens.neutralH})`,
  surface: `oklch(0.9 0.005 ${tokens.neutralH})`,
  hover: `oklch(0.85 0.005 ${tokens.neutralH})`,
  inverse: `oklch(0.18 ${tokens.neutralC} ${tokens.neutralH})`,
  onInverse: `oklch(0.97 calc(${tokens.neutralC} * 0.5) ${tokens.neutralH})`,
  background: `oklch(0.97 0.004 ${tokens.neutralH})`,
};

export const avatar = {
  background: "oklch(0.45 0.09 var(--rk-avatar-h, 260))",
  foreground: "oklch(0.95 0.03 var(--rk-avatar-h, 260))",
};
